/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardDetails {
  'customMessage' : [] | [string],
  'socialLinks' : SocialLinks,
  'name' : string,
  'email' : string,
  'website' : [] | [string],
  'company' : string,
  'jobTitle' : string,
  'phone' : string,
}
export interface CreateOrderRequest {
  'templateId' : TemplateId,
  'cardDetails' : CardDetails,
  'quantity' : OrderQuantity,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'trackingNumber' : [] | [string],
  'paymentAmountCents' : bigint,
  'owner' : Principal,
  'templateId' : TemplateId,
  'createdAt' : Time,
  'cardDetails' : CardDetails,
  'updatedAt' : Time,
  'quantity' : OrderQuantity,
  'stripePaymentIntentId' : [] | [string],
}
export type OrderId = bigint;
export type OrderQuantity = { 'q1000' : null } |
  { 'q2000' : null } |
  { 'q100' : null } |
  { 'q500' : null };
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface SocialLinks {
  'linkedin' : [] | [string],
  'twitter' : [] | [string],
  'instagram' : [] | [string],
}
export interface Template {
  'id' : TemplateId,
  'name' : string,
  'description' : string,
  'previewImageUrl' : string,
}
export type TemplateId = bigint;
export type Time = bigint;
export interface UpdateOrderStatusRequest {
  'status' : OrderStatus,
  'trackingNumber' : [] | [string],
  'orderId' : OrderId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminUpdateOrderStatus' : ActorMethod<[UpdateOrderStatusRequest], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmOrderPayment' : ActorMethod<[OrderId, string], boolean>,
  'createOrder' : ActorMethod<[CreateOrderRequest], Order>,
  'duplicateOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getTemplate' : ActorMethod<[TemplateId], [] | [Template]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listTemplates' : ActorMethod<[], Array<Template>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];