/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const UpdateOrderStatusRequest = IDL.Record({
  'status' : OrderStatus,
  'trackingNumber' : IDL.Opt(IDL.Text),
  'orderId' : OrderId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TemplateId = IDL.Nat;
export const SocialLinks = IDL.Record({
  'linkedin' : IDL.Opt(IDL.Text),
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
});
export const CardDetails = IDL.Record({
  'customMessage' : IDL.Opt(IDL.Text),
  'socialLinks' : SocialLinks,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderQuantity = IDL.Variant({
  'q1000' : IDL.Null,
  'q2000' : IDL.Null,
  'q100' : IDL.Null,
  'q500' : IDL.Null,
});
export const CreateOrderRequest = IDL.Record({
  'templateId' : TemplateId,
  'cardDetails' : CardDetails,
  'quantity' : OrderQuantity,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'trackingNumber' : IDL.Opt(IDL.Text),
  'paymentAmountCents' : IDL.Nat,
  'owner' : IDL.Principal,
  'templateId' : TemplateId,
  'createdAt' : Time,
  'cardDetails' : CardDetails,
  'updatedAt' : Time,
  'quantity' : OrderQuantity,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
});
export const Template = IDL.Record({
  'id' : TemplateId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'previewImageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminUpdateOrderStatus' : IDL.Func(
      [UpdateOrderStatusRequest],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmOrderPayment' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
  'duplicateOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const UpdateOrderStatusRequest = IDL.Record({
    'status' : OrderStatus,
    'trackingNumber' : IDL.Opt(IDL.Text),
    'orderId' : OrderId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TemplateId = IDL.Nat;
  const SocialLinks = IDL.Record({
    'linkedin' : IDL.Opt(IDL.Text),
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
  });
  const CardDetails = IDL.Record({
    'customMessage' : IDL.Opt(IDL.Text),
    'socialLinks' : SocialLinks,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderQuantity = IDL.Variant({
    'q1000' : IDL.Null,
    'q2000' : IDL.Null,
    'q100' : IDL.Null,
    'q500' : IDL.Null,
  });
  const CreateOrderRequest = IDL.Record({
    'templateId' : TemplateId,
    'cardDetails' : CardDetails,
    'quantity' : OrderQuantity,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'trackingNumber' : IDL.Opt(IDL.Text),
    'paymentAmountCents' : IDL.Nat,
    'owner' : IDL.Principal,
    'templateId' : TemplateId,
    'createdAt' : Time,
    'cardDetails' : CardDetails,
    'updatedAt' : Time,
    'quantity' : OrderQuantity,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  });
  const Template = IDL.Record({
    'id' : TemplateId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'previewImageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminUpdateOrderStatus' : IDL.Func(
        [UpdateOrderStatusRequest],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmOrderPayment' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
    'duplicateOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };