/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrderId = bigint;
export type Time = bigint;
export interface CardDetails {
    customMessage?: string;
    socialLinks: SocialLinks;
    name: string;
    email: string;
    website?: string;
    company: string;
    jobTitle: string;
    phone: string;
}
export type TemplateId = bigint;
export interface SocialLinks {
    linkedin?: string;
    twitter?: string;
    instagram?: string;
}
export interface CreateOrderRequest {
    templateId: TemplateId;
    cardDetails: CardDetails;
    quantity: OrderQuantity;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    trackingNumber?: string;
    paymentAmountCents: bigint;
    owner: Principal;
    templateId: TemplateId;
    createdAt: Time;
    cardDetails: CardDetails;
    updatedAt: Time;
    quantity: OrderQuantity;
    stripePaymentIntentId?: string;
}
export interface Template {
    id: TemplateId;
    name: string;
    description: string;
    previewImageUrl: string;
}
export interface UpdateOrderStatusRequest {
    status: OrderStatus;
    trackingNumber?: string;
    orderId: OrderId;
}
export enum OrderQuantity {
    q1000 = "q1000",
    q2000 = "q2000",
    q100 = "q100",
    q500 = "q500"
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    adminUpdateOrderStatus(req: UpdateOrderStatusRequest): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmOrderPayment(orderId: OrderId, stripePaymentIntentId: string): Promise<boolean>;
    createOrder(req: CreateOrderRequest): Promise<Order>;
    duplicateOrder(sourceOrderId: OrderId): Promise<Order | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyOrder(orderId: OrderId): Promise<Order | null>;
    getTemplate(id: TemplateId): Promise<Template | null>;
    isCallerAdmin(): Promise<boolean>;
    listMyOrders(): Promise<Array<Order>>;
    listTemplates(): Promise<Array<Template>>;
}
import type { CardDetails as _CardDetails, CreateOrderRequest as _CreateOrderRequest, Order as _Order, OrderId as _OrderId, OrderQuantity as _OrderQuantity, OrderStatus as _OrderStatus, SocialLinks as _SocialLinks, Template as _Template, TemplateId as _TemplateId, Time as _Time, UpdateOrderStatusRequest as _UpdateOrderStatusRequest, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminUpdateOrderStatus(arg0: UpdateOrderStatusRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(to_candid_UpdateOrderStatusRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(to_candid_UpdateOrderStatusRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmOrderPayment(arg0: OrderId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmOrderPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmOrderPayment(arg0, arg1);
            return result;
        }
    }
    async createOrder(arg0: CreateOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplicateOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateOrder(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateOrder(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrder(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrder(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplate(arg0: TemplateId): Promise<Template | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTemplates(): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTemplates();
            return result;
        }
    }
}
function from_candid_CardDetails_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardDetails): CardDetails {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_OrderQuantity_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderQuantity): OrderQuantity {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SocialLinks_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialLinks): SocialLinks {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Template]): Template | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    trackingNumber: [] | [string];
    paymentAmountCents: bigint;
    owner: Principal;
    templateId: _TemplateId;
    createdAt: _Time;
    cardDetails: _CardDetails;
    updatedAt: _Time;
    quantity: _OrderQuantity;
    stripePaymentIntentId: [] | [string];
}): {
    id: OrderId;
    status: OrderStatus;
    trackingNumber?: string;
    paymentAmountCents: bigint;
    owner: Principal;
    templateId: TemplateId;
    createdAt: Time;
    cardDetails: CardDetails;
    updatedAt: Time;
    quantity: OrderQuantity;
    stripePaymentIntentId?: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        trackingNumber: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.trackingNumber)),
        paymentAmountCents: value.paymentAmountCents,
        owner: value.owner,
        templateId: value.templateId,
        createdAt: value.createdAt,
        cardDetails: from_candid_CardDetails_n20(_uploadFile, _downloadFile, value.cardDetails),
        updatedAt: value.updatedAt,
        quantity: from_candid_OrderQuantity_n24(_uploadFile, _downloadFile, value.quantity),
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.stripePaymentIntentId))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customMessage: [] | [string];
    socialLinks: _SocialLinks;
    name: string;
    email: string;
    website: [] | [string];
    company: string;
    jobTitle: string;
    phone: string;
}): {
    customMessage?: string;
    socialLinks: SocialLinks;
    name: string;
    email: string;
    website?: string;
    company: string;
    jobTitle: string;
    phone: string;
} {
    return {
        customMessage: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.customMessage)),
        socialLinks: from_candid_SocialLinks_n22(_uploadFile, _downloadFile, value.socialLinks),
        name: value.name,
        email: value.email,
        website: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.website)),
        company: value.company,
        jobTitle: value.jobTitle,
        phone: value.phone
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: [] | [string];
    twitter: [] | [string];
    instagram: [] | [string];
}): {
    linkedin?: string;
    twitter?: string;
    instagram?: string;
} {
    return {
        linkedin: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.linkedin)),
        twitter: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.twitter)),
        instagram: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.instagram))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    q1000: null;
} | {
    q2000: null;
} | {
    q100: null;
} | {
    q500: null;
}): OrderQuantity {
    return "q1000" in value ? OrderQuantity.q1000 : "q2000" in value ? OrderQuantity.q2000 : "q100" in value ? OrderQuantity.q100 : "q500" in value ? OrderQuantity.q500 : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n15(_uploadFile, _downloadFile, x));
}
function to_candid_CardDetails_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardDetails): _CardDetails {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderRequest): _CreateOrderRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_OrderQuantity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderQuantity): _OrderQuantity {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SocialLinks_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialLinks): _SocialLinks {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateOrderStatusRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateOrderStatusRequest): _UpdateOrderStatusRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customMessage?: string;
    socialLinks: SocialLinks;
    name: string;
    email: string;
    website?: string;
    company: string;
    jobTitle: string;
    phone: string;
}): {
    customMessage: [] | [string];
    socialLinks: _SocialLinks;
    name: string;
    email: string;
    website: [] | [string];
    company: string;
    jobTitle: string;
    phone: string;
} {
    return {
        customMessage: value.customMessage ? candid_some(value.customMessage) : candid_none(),
        socialLinks: to_candid_SocialLinks_n11(_uploadFile, _downloadFile, value.socialLinks),
        name: value.name,
        email: value.email,
        website: value.website ? candid_some(value.website) : candid_none(),
        company: value.company,
        jobTitle: value.jobTitle,
        phone: value.phone
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin?: string;
    twitter?: string;
    instagram?: string;
}): {
    linkedin: [] | [string];
    twitter: [] | [string];
    instagram: [] | [string];
} {
    return {
        linkedin: value.linkedin ? candid_some(value.linkedin) : candid_none(),
        twitter: value.twitter ? candid_some(value.twitter) : candid_none(),
        instagram: value.instagram ? candid_some(value.instagram) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: OrderStatus;
    trackingNumber?: string;
    orderId: OrderId;
}): {
    status: _OrderStatus;
    trackingNumber: [] | [string];
    orderId: _OrderId;
} {
    return {
        status: to_candid_OrderStatus_n3(_uploadFile, _downloadFile, value.status),
        trackingNumber: value.trackingNumber ? candid_some(value.trackingNumber) : candid_none(),
        orderId: value.orderId
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    templateId: TemplateId;
    cardDetails: CardDetails;
    quantity: OrderQuantity;
}): {
    templateId: _TemplateId;
    cardDetails: _CardDetails;
    quantity: _OrderQuantity;
} {
    return {
        templateId: value.templateId,
        cardDetails: to_candid_CardDetails_n9(_uploadFile, _downloadFile, value.cardDetails),
        quantity: to_candid_OrderQuantity_n13(_uploadFile, _downloadFile, value.quantity)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderQuantity): {
    q1000: null;
} | {
    q2000: null;
} | {
    q100: null;
} | {
    q500: null;
} {
    return value == OrderQuantity.q1000 ? {
        q1000: null
    } : value == OrderQuantity.q2000 ? {
        q2000: null
    } : value == OrderQuantity.q100 ? {
        q100: null
    } : value == OrderQuantity.q500 ? {
        q500: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
